import { Quote, MeditationSession } from './api';

export const MOCK_QUOTES: Quote[] = [
  // BUDDHIST WISDOM - Pali Canon (Dhammapada)
  {
    id: 1,
    text: 'मनो पुब्बङ्गमा धम्मा मनो सेट्ठा मनोमया।',
    textTransliteration: 'Mano pubbaṅgamā dhammā mano seṭṭhā manomayā.',
    translations: {
      en: 'Mind is the forerunner of all things. All things are mind-made.',
      pl: 'Umysł jest prekursorem wszystkich rzeczy. Wszystko jest stworzone przez umysł.',
      de: 'Der Geist ist der Vorläufer aller Dinge. Alle Dinge sind vom Geist geschaffen.',
      es: 'La mente es la precursora de todas las cosas. Todo está creado por la mente.',
      fr: 'L\'esprit est le précurseur de toutes choses. Tout est créé par l\'esprit.',
      hi: 'मन सभी चीजों का अग्रदूत है। सभी चीजें मन से बनी हैं।',
      zh: '心為諸法先導，心為主，心所成。',
    },
    originalLanguage: 'pi',
    author: 'Buddha (Dhammapada)',
    cultureTag: 'buddhist',
    category: 'Wisdom',
    createdAt: new Date().toISOString(),
  },
  {
    id: 2,
    text: 'सब्बे संखारा अनिच्चाति।',
    textTransliteration: 'Sabbe saṅkhārā aniccāti.',
    translations: {
      en: 'All conditioned things are impermanent.',
      pl: 'Wszystkie uwarunkowane rzeczy są nietrwałe.',
      de: 'Alle bedingten Dinge sind vergänglich.',
      es: 'Todas las cosas condicionadas son impermanentes.',
      fr: 'Toutes les choses conditionnées sont impermanentes.',
      hi: 'सभी संस्कारित चीजें अनित्य हैं।',
      zh: '諸行無常。',
    },
    originalLanguage: 'pi',
    author: 'Buddha (Dhammapada)',
    cultureTag: 'buddhist',
    category: 'Wisdom',
    createdAt: new Date().toISOString(),
  },
  {
    id: 3,
    text: 'अप्पमादो अमतपदं पमादो मच्चुनो पदं।',
    textTransliteration: 'Appamādo amatapadaṃ pamādo maccuno padaṃ.',
    translations: {
      en: 'Mindfulness is the path to immortality. Heedlessness is the path to death.',
      pl: 'Uważność jest ścieżką do nieśmiertelności. Nieuważność jest ścieżką do śmierci.',
      de: 'Achtsamkeit ist der Pfad zur Unsterblichkeit. Achtlosigkeit ist der Pfad zum Tod.',
      es: 'La atención plena es el camino a la inmortalidad. La negligencia es el camino a la muerte.',
      fr: 'La pleine conscience est le chemin vers l\'immortalité. La négligence est le chemin vers la mort.',
      hi: 'सावधानी अमरता का मार्ग है। असावधानी मृत्यु का मार्ग है।',
      zh: '不放逸為不死之道，放逸為死之道。',
    },
    originalLanguage: 'pi',
    author: 'Buddha (Dhammapada)',
    cultureTag: 'buddhist',
    category: 'Mindfulness',
    createdAt: new Date().toISOString(),
  },

  // BUDDHIST WISDOM - Sanskrit Mahayana
  {
    id: 4,
    text: 'शून्यता सर्वदृष्टीनां प्रोक्ता निःसरणं जिनैः।',
    textTransliteration: 'Śūnyatā sarvadṛṣṭīnāṃ proktā niḥsaraṇaṃ jinaiḥ.',
    translations: {
      en: 'Emptiness is proclaimed by the victorious ones as the freedom from all views.',
      pl: 'Pustka jest głoszona przez zwycięzców jako wolność od wszystkich poglądów.',
      de: 'Leerheit wird von den Siegreichen als Befreiung von allen Ansichten verkündet.',
      es: 'El vacío es proclamado por los victoriosos como la liberación de todas las visiones.',
      fr: 'La vacuité est proclamée par les victorieux comme la libération de toutes les vues.',
      hi: 'शून्यता को विजेताओं द्वारा सभी दृष्टिकोणों से मुक्ति के रूप में घोषित किया गया है।',
      zh: '空性是諸佛宣說的，從一切見解中解脫。',
    },
    originalLanguage: 'sa',
    author: 'Nagarjuna',
    cultureTag: 'buddhist',
    category: 'Wisdom',
    createdAt: new Date().toISOString(),
  },
  {
    id: 5,
    text: 'सर्वे भवन्तु सुखिनः सर्वे सन्तु निरामयाः।',
    textTransliteration: 'Sarve bhavantu sukhinaḥ sarve santu nirāmayāḥ.',
    translations: {
      en: 'May all beings be happy. May all beings be free from illness.',
      pl: 'Niech wszystkie istoty będą szczęśliwe. Niech wszystkie istoty będą wolne od chorób.',
      de: 'Mögen alle Wesen glücklich sein. Mögen alle Wesen frei von Krankheit sein.',
      es: 'Que todos los seres sean felices. Que todos los seres estén libres de enfermedad.',
      fr: 'Que tous les êtres soient heureux. Que tous les êtres soient libres de maladie.',
      hi: 'सभी जीव सुखी हों। सभी जीव रोगमुक्त हों।',
      zh: '願一切眾生快樂。願一切眾生無病。',
    },
    originalLanguage: 'sa',
    author: 'Buddhist Metta Prayer',
    cultureTag: 'buddhist',
    category: 'Compassion',
    createdAt: new Date().toISOString(),
  },
  {
    id: 6,
    text: 'यावन्ति दुःखानि सर्वाणि तानि स्वात्मपरित्यागात्।',
    textTransliteration: 'Yāvanti duḥkhāni sarvāṇi tāni svātmaparityāgāt.',
    translations: {
      en: 'All suffering comes from cherishing ourselves. All happiness comes from cherishing others.',
      pl: 'Całe cierpienie pochodzi z troski o siebie. Całe szczęście pochodzi z troski o innych.',
      de: 'Alles Leiden kommt vom Festhalten am Selbst. Alles Glück kommt vom Wertschätzen anderer.',
      es: 'Todo sufrimiento viene de apreciarnos a nosotros mismos. Toda felicidad viene de apreciar a otros.',
      fr: 'Toute souffrance vient de se chérir soi-même. Tout bonheur vient de chérir les autres.',
      hi: 'सभी दुःख स्वयं की परवाह से आते हैं। सभी सुख दूसरों की परवाह से आते हैं।',
      zh: '一切苦源於珍愛自我。一切樂源於珍愛他人。',
    },
    originalLanguage: 'sa',
    author: 'Shantideva',
    cultureTag: 'buddhist',
    category: 'Compassion',
    createdAt: new Date().toISOString(),
  },

  // VEDIC/HINDU WISDOM - Bhagavad Gita
  {
    id: 7,
    text: 'योगस्थः कुरु कर्माणि सङ्गं त्यक्त्वा धनञ्जय।',
    textTransliteration: 'Yogasthaḥ kuru karmāṇi saṅgaṃ tyaktvā dhanañjaya.',
    translations: {
      en: 'Established in yoga, perform actions, abandoning attachment.',
      pl: 'Ugruntowany w jodze, wykonuj czyny, porzucając przywiązanie.',
      de: 'Im Yoga verankert, führe Handlungen aus, indem du Anhaftung aufgibst.',
      es: 'Establecido en yoga, realiza acciones, abandonando el apego.',
      fr: 'Établi dans le yoga, accomplis des actions, en abandonnant l\'attachement.',
      hi: 'योग में स्थित होकर कर्म करो, आसक्ति त्यागकर।',
      zh: '安住於瑜伽中行動，捨棄執著。',
    },
    originalLanguage: 'sa',
    author: 'Bhagavad Gita 2.48',
    cultureTag: 'vedic',
    category: 'Practice',
    createdAt: new Date().toISOString(),
  },
  {
    id: 8,
    text: 'यदा यदा हि धर्मस्य ग्लानिर्भवति भारत।',
    textTransliteration: 'Yadā yadā hi dharmasya glānirbhavati bhārata.',
    translations: {
      en: 'Whenever there is a decline in righteousness, I manifest myself.',
      pl: 'Ilekroć następuje upadek prawości, objawiasz się.',
      de: 'Wann immer die Rechtschaffenheit abnimmt, manifestiere ich mich.',
      es: 'Siempre que hay un declive en la rectitud, me manifiesto.',
      fr: 'Chaque fois qu\'il y a un déclin de la droiture, je me manifeste.',
      hi: 'जब-जब धर्म की हानि होती है, मैं प्रकट होता हूं।',
      zh: '每當正法衰微時，我即顯現。',
    },
    originalLanguage: 'sa',
    author: 'Bhagavad Gita 4.7',
    cultureTag: 'vedic',
    category: 'Wisdom',
    createdAt: new Date().toISOString(),
  },
  {
    id: 9,
    text: 'कर्मण्येवाधिकारस्ते मा फलेषु कदाचन।',
    textTransliteration: 'Karmaṇyevādhikāraste mā phaleṣu kadācana.',
    translations: {
      en: 'You have the right to action alone, never to its fruits.',
      pl: 'Masz prawo tylko do działania, nigdy do jego owoców.',
      de: 'Du hast ein Recht auf die Handlung allein, niemals auf ihre Früchte.',
      es: 'Tienes derecho solo a la acción, nunca a sus frutos.',
      fr: 'Tu as le droit à l\'action seule, jamais à ses fruits.',
      hi: 'तुम्हारा अधिकार केवल कर्म में है, फल में कभी नहीं।',
      zh: '你只有行動的權利，絕不是其果實。',
    },
    originalLanguage: 'sa',
    author: 'Bhagavad Gita 2.47',
    cultureTag: 'vedic',
    category: 'Wisdom',
    createdAt: new Date().toISOString(),
  },

  // VEDIC WISDOM - Upanishads
  {
    id: 10,
    text: 'तत् त्वम् असि।',
    textTransliteration: 'Tat tvam asi.',
    translations: {
      en: 'That thou art. You are That.',
      pl: 'Ty jesteś Tym.',
      de: 'Das bist du.',
      es: 'Tú eres Eso.',
      fr: 'Tu es Cela.',
      hi: 'तत् त्वम् असि। तुम वही हो।',
      zh: '你即是那。',
    },
    originalLanguage: 'sa',
    author: 'Chandogya Upanishad',
    cultureTag: 'vedic',
    category: 'Wisdom',
    createdAt: new Date().toISOString(),
  },
  {
    id: 11,
    text: 'असतो मा सद्गमय। तमसो मा ज्योतिर्गमय।',
    textTransliteration: 'Asato mā sadgamaya. Tamaso mā jyotirgamaya.',
    translations: {
      en: 'Lead me from the unreal to the real. Lead me from darkness to light.',
      pl: 'Prowadź mnie od nierzeczywistego do rzeczywistego. Prowadź mnie od ciemności do światła.',
      de: 'Führe mich vom Unwirklichen zum Wirklichen. Führe mich von der Dunkelheit zum Licht.',
      es: 'Guíame de lo irreal a lo real. Guíame de la oscuridad a la luz.',
      fr: 'Conduis-moi de l\'irréel au réel. Conduis-moi des ténèbres à la lumière.',
      hi: 'असत्य से सत्य की ओर ले चलो। अंधकार से प्रकाश की ओर ले चलो।',
      zh: '引我從虛幻至真實。引我從黑暗至光明。',
    },
    originalLanguage: 'sa',
    author: 'Brihadaranyaka Upanishad',
    cultureTag: 'vedic',
    category: 'Wisdom',
    createdAt: new Date().toISOString(),
  },
  {
    id: 12,
    text: 'योगश्चित्तवृत्तिनिरोधः।',
    textTransliteration: 'Yogaścittavṛttinirodhaḥ.',
    translations: {
      en: 'Yoga is the cessation of the fluctuations of the mind.',
      pl: 'Joga to ustanie wahań umysłu.',
      de: 'Yoga ist das Zur-Ruhe-Bringen der Bewegungen des Geistes.',
      es: 'El yoga es el cese de las fluctuaciones de la mente.',
      fr: 'Le yoga est la cessation des fluctuations du mental.',
      hi: 'योग चित्त की वृत्तियों का निरोध है।',
      zh: '瑜伽即心念波動之止息。',
    },
    originalLanguage: 'sa',
    author: 'Patanjali Yoga Sutras 1.2',
    cultureTag: 'vedic',
    category: 'Practice',
    createdAt: new Date().toISOString(),
  },

  // ZEN WISDOM - Japanese
  {
    id: 13,
    text: '身心脱落',
    textTransliteration: 'Shinjin datsuraku',
    translations: {
      en: 'Dropping off body and mind.',
      pl: 'Odrzucenie ciała i umysłu.',
      de: 'Abwerfen von Körper und Geist.',
      es: 'Desprenderse del cuerpo y la mente.',
      fr: 'Laisser tomber le corps et l\'esprit.',
      hi: 'शरीर और मन को छोड़ देना।',
      zh: '身心脫落。',
    },
    originalLanguage: 'ja',
    author: 'Dogen Zenji',
    cultureTag: 'zen',
    category: 'Practice',
    createdAt: new Date().toISOString(),
  },
  {
    id: 14,
    text: '只管打坐',
    textTransliteration: 'Shikantaza',
    translations: {
      en: 'Just sit. Nothing but sitting.',
      pl: 'Po prostu siedź. Nic poza siedzeniem.',
      de: 'Einfach nur sitzen. Nichts als sitzen.',
      es: 'Solo siéntate. Nada más que sentarse.',
      fr: 'Simplement s\'asseoir. Rien que s\'asseoir.',
      hi: 'बस बैठो। बैठने के अलावा कुछ नहीं।',
      zh: '只管打坐。唯有坐禪。',
    },
    originalLanguage: 'ja',
    author: 'Dogen Zenji',
    cultureTag: 'zen',
    category: 'Practice',
    createdAt: new Date().toISOString(),
  },
  {
    id: 15,
    text: '古池や蛙飛びこむ水の音',
    textTransliteration: 'Furuike ya kawazu tobikomu mizu no oto',
    translations: {
      en: 'The ancient pond. A frog jumps in. The sound of water.',
      pl: 'Stary staw. Żaba wskakuje. Dźwięk wody.',
      de: 'Der alte Teich. Ein Frosch springt hinein. Das Geräusch des Wassers.',
      es: 'El estanque antiguo. Una rana salta. El sonido del agua.',
      fr: 'L\'étang ancien. Une grenouille saute. Le son de l\'eau.',
      hi: 'प्राचीन तालाब। एक मेंढक कूदता है। पानी की आवाज़।',
      zh: '古池塘。青蛙跳入。水之聲。',
    },
    originalLanguage: 'ja',
    author: 'Matsuo Basho',
    cultureTag: 'zen',
    category: 'Mindfulness',
    createdAt: new Date().toISOString(),
  },
  {
    id: 16,
    text: '初心忘るべからず',
    textTransliteration: 'Shoshin wasuru bekarazu',
    translations: {
      en: 'Never forget the beginner\'s mind.',
      pl: 'Nigdy nie zapominaj umysłu początkującego.',
      de: 'Vergiss niemals den Anfängergeist.',
      es: 'Nunca olvides la mente de principiante.',
      fr: 'N\'oublie jamais l\'esprit du débutant.',
      hi: 'शुरुआती मन को कभी मत भूलो।',
      zh: '莫忘初心。',
    },
    originalLanguage: 'ja',
    author: 'Zeami',
    cultureTag: 'zen',
    category: 'Wisdom',
    createdAt: new Date().toISOString(),
  },
  {
    id: 17,
    text: '無心',
    textTransliteration: 'Mushin',
    translations: {
      en: 'No-mind. Mind without mind.',
      pl: 'Nie-umysł. Umysł bez umysłu.',
      de: 'Nicht-Geist. Geist ohne Geist.',
      es: 'No-mente. Mente sin mente.',
      fr: 'Non-esprit. Esprit sans esprit.',
      hi: 'निर्विचार। मन के बिना मन।',
      zh: '無心。無念之心。',
    },
    originalLanguage: 'ja',
    author: 'Zen Teaching',
    cultureTag: 'zen',
    category: 'Stillness',
    createdAt: new Date().toISOString(),
  },

  // TAOIST WISDOM - Classical Chinese
  {
    id: 18,
    text: '道可道，非常道。',
    textTransliteration: 'Dào kě dào, fēi cháng dào.',
    translations: {
      en: 'The Tao that can be spoken is not the eternal Tao.',
      pl: 'Tao, które można wypowiedzieć, nie jest wiecznym Tao.',
      de: 'Das Tao, das ausgesprochen werden kann, ist nicht das ewige Tao.',
      es: 'El Tao que puede ser hablado no es el Tao eterno.',
      fr: 'Le Tao qui peut être exprimé n\'est pas le Tao éternel.',
      hi: 'जो ताओ कहा जा सके, वह शाश्वत ताओ नहीं है।',
      zh: '道可道，非常道。',
    },
    originalLanguage: 'zh',
    author: 'Lao Tzu (Tao Te Ching 1)',
    cultureTag: 'taoist',
    category: 'Wisdom',
    createdAt: new Date().toISOString(),
  },
  {
    id: 19,
    text: '上善若水。',
    textTransliteration: 'Shàng shàn ruò shuǐ.',
    translations: {
      en: 'The highest good is like water.',
      pl: 'Najwyższe dobro jest jak woda.',
      de: 'Das höchste Gut ist wie Wasser.',
      es: 'El bien supremo es como el agua.',
      fr: 'Le bien suprême est comme l\'eau.',
      hi: 'सर्वोच्च अच्छाई पानी की तरह है।',
      zh: '上善若水。',
    },
    originalLanguage: 'zh',
    author: 'Lao Tzu (Tao Te Ching 8)',
    cultureTag: 'taoist',
    category: 'Wisdom',
    createdAt: new Date().toISOString(),
  },
  {
    id: 20,
    text: '知者不言，言者不知。',
    textTransliteration: 'Zhī zhě bù yán, yán zhě bù zhī.',
    translations: {
      en: 'Those who know do not speak. Those who speak do not know.',
      pl: 'Ci, którzy wiedzą, nie mówią. Ci, którzy mówią, nie wiedzą.',
      de: 'Die Wissenden sprechen nicht. Die Sprechenden wissen nicht.',
      es: 'Los que saben no hablan. Los que hablan no saben.',
      fr: 'Ceux qui savent ne parlent pas. Ceux qui parlent ne savent pas.',
      hi: 'जो जानते हैं वे नहीं बोलते। जो बोलते हैं वे नहीं जानते।',
      zh: '知者不言，言者不知。',
    },
    originalLanguage: 'zh',
    author: 'Lao Tzu (Tao Te Ching 56)',
    cultureTag: 'taoist',
    category: 'Stillness',
    createdAt: new Date().toISOString(),
  },
  {
    id: 21,
    text: '無為而無不為。',
    textTransliteration: 'Wú wéi ér wú bù wéi.',
    translations: {
      en: 'Do nothing, and nothing is left undone.',
      pl: 'Nie rób nic, a nic nie pozostanie niezrobione.',
      de: 'Tue nichts, und nichts bleibt ungetan.',
      es: 'No hagas nada, y nada queda sin hacer.',
      fr: 'Ne fais rien, et rien n\'est laissé non fait.',
      hi: 'कुछ मत करो, और कुछ भी अधूरा नहीं रहेगा।',
      zh: '無為而無不為。',
    },
    originalLanguage: 'zh',
    author: 'Lao Tzu (Tao Te Ching 48)',
    cultureTag: 'taoist',
    category: 'Practice',
    createdAt: new Date().toISOString(),
  },
  {
    id: 22,
    text: '天地不仁，以萬物為芻狗。',
    textTransliteration: 'Tiān dì bù rén, yǐ wàn wù wéi chú gǒu.',
    translations: {
      en: 'Heaven and Earth are impartial. They treat all things as straw dogs.',
      pl: 'Niebo i Ziemia są bezstronne. Traktują wszystkie rzeczy jak słomiane psy.',
      de: 'Himmel und Erde sind unparteiisch. Sie behandeln alle Dinge wie Strohhunde.',
      es: 'El Cielo y la Tierra son imparciales. Tratan todas las cosas como perros de paja.',
      fr: 'Le Ciel et la Terre sont impartiaux. Ils traitent toutes choses comme des chiens de paille.',
      hi: 'स्वर्ग और पृथ्वी निष्पक्ष हैं। वे सभी चीजों को तिनके के कुत्तों की तरह मानते हैं।',
      zh: '天地不仁，以萬物為芻狗。',
    },
    originalLanguage: 'zh',
    author: 'Lao Tzu (Tao Te Ching 5)',
    cultureTag: 'taoist',
    category: 'Wisdom',
    createdAt: new Date().toISOString(),
  },

  // SUFI WISDOM - Persian
  {
    id: 23,
    text: 'دیروز هوشیار بودم خواستم دنیا را عوض کنم، امروز خردمندم خودم را عوض میکنم.',
    textTransliteration: 'Diruz hushyar budam khastam dunya ra avaz konam, emruz kherad-mandam khodam ra avaz mikonam.',
    translations: {
      en: 'Yesterday I was clever, so I wanted to change the world. Today I am wise, so I am changing myself.',
      pl: 'Wczoraj byłem mądry, więc chciałem zmienić świat. Dziś jestem mądry, więc zmieniam siebie.',
      de: 'Gestern war ich klug, also wollte ich die Welt verändern. Heute bin ich weise, also verändere ich mich selbst.',
      es: 'Ayer era inteligente, así que quería cambiar el mundo. Hoy soy sabio, así que me estoy cambiando a mí mismo.',
      fr: 'Hier j\'étais intelligent, alors je voulais changer le monde. Aujourd\'hui je suis sage, alors je me change moi-même.',
      hi: 'कल मैं चतुर था, इसलिए मैं दुनिया बदलना चाहता था। आज मैं बुद्धिमान हूं, इसलिए मैं खुद को बदल रहा हूं।',
      zh: '昨日我聰慧，故欲改變世界。今日我智慧，故改變自己。',
    },
    originalLanguage: 'fa',
    author: 'Rumi',
    cultureTag: 'sufi',
    category: 'Wisdom',
    createdAt: new Date().toISOString(),
  },
  {
    id: 24,
    text: 'سکوت زبان عارفان است.',
    textTransliteration: 'Sokut zaban-e arefan ast.',
    translations: {
      en: 'Silence is the language of the mystics.',
      pl: 'Cisza jest językiem mistyków.',
      de: 'Stille ist die Sprache der Mystiker.',
      es: 'El silencio es el lenguaje de los místicos.',
      fr: 'Le silence est le langage des mystiques.',
      hi: 'मौन रहस्यवादियों की भाषा है।',
      zh: '沉默是神秘主義者的語言。',
    },
    originalLanguage: 'fa',
    author: 'Rumi',
    cultureTag: 'sufi',
    category: 'Stillness',
    createdAt: new Date().toISOString(),
  },
  {
    id: 25,
    text: 'زخم همان جائیست که نور وارد میشود.',
    textTransliteration: 'Zakhm haman ja-ist ke nur vared mishavad.',
    translations: {
      en: 'The wound is where the light enters you.',
      pl: 'Rana jest miejscem, gdzie światło do ciebie wchodzi.',
      de: 'Die Wunde ist der Ort, an dem das Licht in dich eintritt.',
      es: 'La herida es donde la luz entra en ti.',
      fr: 'La blessure est l\'endroit où la lumière entre en toi.',
      hi: 'घाव वह जगह है जहां प्रकाश आप में प्रवेश करता है।',
      zh: '傷口是光進入你之處。',
    },
    originalLanguage: 'fa',
    author: 'Rumi',
    cultureTag: 'sufi',
    category: 'Healing',
    createdAt: new Date().toISOString(),
  },
  {
    id: 26,
    text: 'ترس ارزان‌ترین اتاق در خانه است.',
    textTransliteration: 'Tars arzan-tarin otaq dar khane ast.',
    translations: {
      en: 'Fear is the cheapest room in the house.',
      pl: 'Strach jest najtańszym pokojem w domu.',
      de: 'Angst ist das billigste Zimmer im Haus.',
      es: 'El miedo es la habitación más barata de la casa.',
      fr: 'La peur est la chambre la moins chère de la maison.',
      hi: 'डर घर का सबसे सस्ता कमरा है।',
      zh: '恐懼是屋中最廉價的房間。',
    },
    originalLanguage: 'fa',
    author: 'Hafiz',
    cultureTag: 'sufi',
    category: 'Courage',
    createdAt: new Date().toISOString(),
  },
  {
    id: 27,
    text: 'الفَقْرُ فَخْرِي',
    textTransliteration: 'Al-faqru fakhri',
    translations: {
      en: 'Poverty is my pride. Spiritual emptiness is my wealth.',
      pl: 'Ubóstwo jest moją dumą. Duchowa pustka jest moim bogactwem.',
      de: 'Armut ist mein Stolz. Spirituelle Leere ist mein Reichtum.',
      es: 'La pobreza es mi orgullo. El vacío espiritual es mi riqueza.',
      fr: 'La pauvreté est ma fierté. Le vide spirituel est ma richesse.',
      hi: 'गरीबी मेरा गर्व है। आध्यात्मिक शून्यता मेरा धन है।',
      zh: '貧窮是我的驕傲。靈性空無是我的財富。',
    },
    originalLanguage: 'ar',
    author: 'Sufi Teaching',
    cultureTag: 'sufi',
    category: 'Wisdom',
    createdAt: new Date().toISOString(),
  },
  {
    id: 28,
    text: 'القَلْبُ بَيْتُ الرَّبِّ',
    textTransliteration: 'Al-qalbu baytu al-rabb',
    translations: {
      en: 'The heart is the house of the Lord.',
      pl: 'Serce jest domem Pana.',
      de: 'Das Herz ist das Haus des Herrn.',
      es: 'El corazón es la casa del Señor.',
      fr: 'Le cœur est la maison du Seigneur.',
      hi: 'हृदय प्रभु का घर है।',
      zh: '心是主的居所。',
    },
    originalLanguage: 'ar',
    author: 'Al-Ghazali',
    cultureTag: 'sufi',
    category: 'Inner Peace',
    createdAt: new Date().toISOString(),
  },

  // STOIC WISDOM - Latin
  {
    id: 29,
    text: 'Memento mori.',
    translations: {
      en: 'Remember that you will die. Remember death.',
      pl: 'Pamiętaj, że umrzesz. Pamiętaj o śmierci.',
      de: 'Erinnere dich, dass du sterben wirst. Gedenke des Todes.',
      es: 'Recuerda que morirás. Recuerda la muerte.',
      fr: 'Souviens-toi que tu mourras. Souviens-toi de la mort.',
      hi: 'याद रखें कि आप मर जाएंगे। मृत्यु को याद रखें।',
      zh: '記住你會死。記住死亡。',
    },
    originalLanguage: 'la',
    author: 'Stoic Teaching',
    cultureTag: 'stoic',
    category: 'Mindfulness',
    createdAt: new Date().toISOString(),
  },
  {
    id: 30,
    text: 'Amor fati.',
    translations: {
      en: 'Love of fate. Love what is.',
      pl: 'Miłość do losu. Kochaj to, co jest.',
      de: 'Liebe zum Schicksal. Liebe was ist.',
      es: 'Amor al destino. Ama lo que es.',
      fr: 'Amour du destin. Aime ce qui est.',
      hi: 'भाग्य से प्रेम। जो है उससे प्यार करो।',
      zh: '愛命運。愛現狀。',
    },
    originalLanguage: 'la',
    author: 'Marcus Aurelius',
    cultureTag: 'stoic',
    category: 'Acceptance',
    createdAt: new Date().toISOString(),
  },
  {
    id: 31,
    text: 'Plus dolet quam necesse est qui ante dolet quam necesse est.',
    translations: {
      en: 'He suffers more than necessary, who suffers before it is necessary.',
      pl: 'Więcej cierpi niż trzeba, kto cierpi zanim jest to konieczne.',
      de: 'Er leidet mehr als nötig, wer leidet, bevor es nötig ist.',
      es: 'Sufre más de lo necesario quien sufre antes de que sea necesario.',
      fr: 'Il souffre plus que nécessaire, celui qui souffre avant qu\'il ne soit nécessaire.',
      hi: 'वह आवश्यकता से अधिक पीड़ित है जो आवश्यकता से पहले पीड़ित है।',
      zh: '於必要之前受苦者，受苦甚於必要。',
    },
    originalLanguage: 'la',
    author: 'Seneca',
    cultureTag: 'stoic',
    category: 'Wisdom',
    createdAt: new Date().toISOString(),
  },
  {
    id: 32,
    text: 'Non est ad astra mollis e terris via.',
    translations: {
      en: 'There is no easy way from the earth to the stars.',
      pl: 'Nie ma łatwej drogi z ziemi do gwiazd.',
      de: 'Es gibt keinen leichten Weg von der Erde zu den Sternen.',
      es: 'No hay un camino fácil de la tierra a las estrellas.',
      fr: 'Il n\'y a pas de chemin facile de la terre aux étoiles.',
      hi: 'पृथ्वी से तारों तक कोई आसान रास्ता नहीं है।',
      zh: '從地球到星辰，沒有坦途。',
    },
    originalLanguage: 'la',
    author: 'Seneca',
    cultureTag: 'stoic',
    category: 'Wisdom',
    createdAt: new Date().toISOString(),
  },

  // STOIC WISDOM - Greek
  {
    id: 33,
    text: 'Οὐ τὰ πράγματα ταράσσει τοὺς ἀνθρώπους, ἀλλὰ τὰ περὶ τῶν πραγμάτων δόγματα.',
    textTransliteration: 'Ou ta pragmata tarassei tous anthropous, alla ta peri ton pragmaton dogmata.',
    translations: {
      en: 'It is not things that disturb people, but their judgments about things.',
      pl: 'To nie rzeczy niepokoja ludzi, ale ich osądy o rzeczach.',
      de: 'Nicht die Dinge beunruhigen die Menschen, sondern ihre Urteile über die Dinge.',
      es: 'No son las cosas las que perturban a las personas, sino sus juicios sobre las cosas.',
      fr: 'Ce ne sont pas les choses qui troublent les gens, mais leurs jugements sur les choses.',
      hi: 'लोगों को परेशान करने वाली चीजें नहीं हैं, बल्कि चीजों के बारे में उनके निर्णय हैं।',
      zh: '擾亂人心的不是事物本身，而是對事物的判斷。',
    },
    originalLanguage: 'el',
    author: 'Epictetus',
    cultureTag: 'stoic',
    category: 'Wisdom',
    createdAt: new Date().toISOString(),
  },

  // CHRISTIAN CONTEMPLATIVE - Latin
  {
    id: 34,
    text: 'Silentium est laudatio Dei.',
    translations: {
      en: 'Silence is the praise of God.',
      pl: 'Cisza jest uwielbieniem Boga.',
      de: 'Stille ist das Lob Gottes.',
      es: 'El silencio es la alabanza de Dios.',
      fr: 'Le silence est la louange de Dieu.',
      hi: 'मौन ईश्वर की स्तुति है।',
      zh: '沉默是對神的讚美。',
    },
    originalLanguage: 'la',
    author: 'Desert Fathers',
    cultureTag: 'christian',
    category: 'Stillness',
    createdAt: new Date().toISOString(),
  },
  {
    id: 35,
    text: 'Ora et labora.',
    translations: {
      en: 'Pray and work.',
      pl: 'Módl się i pracuj.',
      de: 'Bete und arbeite.',
      es: 'Ora y trabaja.',
      fr: 'Prie et travaille.',
      hi: 'प्रार्थना करो और काम करो।',
      zh: '祈禱與勞動。',
    },
    originalLanguage: 'la',
    author: 'Benedict of Nursia',
    cultureTag: 'christian',
    category: 'Practice',
    createdAt: new Date().toISOString(),
  },

  // CHRISTIAN CONTEMPLATIVE - German
  {
    id: 36,
    text: 'Gott ist ein reines Nichts, ihn rührt kein Nun noch Hier.',
    translations: {
      en: 'God is a pure Nothing, untouched by now or here.',
      pl: 'Bóg jest czystą Nicością, nienaruszoną przez teraz lub tutaj.',
      de: 'Gott ist ein reines Nichts, ihn rührt kein Nun noch Hier.',
      es: 'Dios es una Nada pura, no tocada por el ahora ni el aquí.',
      fr: 'Dieu est un pur Néant, non touché par le maintenant ou l\'ici.',
      hi: 'ईश्वर एक शुद्ध शून्य है, जिसे अब या यहां से छुआ नहीं गया है।',
      zh: '神是純然的虛無，不為此時此地所觸。',
    },
    originalLanguage: 'de',
    author: 'Meister Eckhart',
    cultureTag: 'christian',
    category: 'Mysticism',
    createdAt: new Date().toISOString(),
  },
  {
    id: 37,
    text: 'Die Stille ist Gottes erste Sprache.',
    translations: {
      en: 'Silence is God\'s first language.',
      pl: 'Cisza jest pierwszym językiem Boga.',
      de: 'Die Stille ist Gottes erste Sprache.',
      es: 'El silencio es el primer idioma de Dios.',
      fr: 'Le silence est le premier langage de Dieu.',
      hi: 'मौन ईश्वर की पहली भाषा है।',
      zh: '沉默是神的首要語言。',
    },
    originalLanguage: 'de',
    author: 'Meister Eckhart',
    cultureTag: 'christian',
    category: 'Stillness',
    createdAt: new Date().toISOString(),
  },

  // CONTEMPORARY WISDOM - English
  {
    id: 38,
    text: 'Be here now.',
    translations: {
      en: 'Be here now.',
      pl: 'Bądź tu i teraz.',
      de: 'Sei hier und jetzt.',
      es: 'Estar aquí ahora.',
      fr: 'Sois ici maintenant.',
      hi: 'अभी यहाँ रहो।',
      zh: '活在當下。',
    },
    originalLanguage: 'en',
    author: 'Ram Dass',
    cultureTag: 'contemporary',
    category: 'Presence',
    createdAt: new Date().toISOString(),
  },
  {
    id: 39,
    text: 'The present moment is the only time over which we have dominion.',
    translations: {
      en: 'The present moment is the only time over which we have dominion.',
      pl: 'Obecna chwila jest jedynym czasem, nad którym mamy panowanie.',
      de: 'Der gegenwärtige Moment ist die einzige Zeit, über die wir Herrschaft haben.',
      es: 'El momento presente es el único tiempo sobre el que tenemos dominio.',
      fr: 'Le moment présent est le seul temps sur lequel nous avons autorité.',
      hi: 'वर्तमान क्षण ही एकमात्र समय है जिस पर हमारा अधिकार है।',
      zh: '當下是我們唯一能掌握的時刻。',
    },
    originalLanguage: 'en',
    author: 'Thich Nhat Hanh',
    cultureTag: 'contemporary',
    category: 'Mindfulness',
    createdAt: new Date().toISOString(),
  },
  {
    id: 40,
    text: 'Wherever you are, be there totally.',
    translations: {
      en: 'Wherever you are, be there totally.',
      pl: 'Gdziekolwiek jesteś, bądź tam całkowicie.',
      de: 'Wo immer du bist, sei dort vollkommen.',
      es: 'Dondequiera que estés, está allí totalmente.',
      fr: 'Où que tu sois, sois-y totalement.',
      hi: 'जहां कहीं भी आप हों, वहां पूरी तरह से रहें।',
      zh: '無論你在哪裡，全然地在那裡。',
    },
    originalLanguage: 'en',
    author: 'Eckhart Tolle',
    cultureTag: 'contemporary',
    category: 'Presence',
    createdAt: new Date().toISOString(),
  },
  {
    id: 41,
    text: 'Meditation is not evasion; it is a serene encounter with reality.',
    translations: {
      en: 'Meditation is not evasion; it is a serene encounter with reality.',
      pl: 'Medytacja to nie ucieczka; to spokojne spotkanie z rzeczywistością.',
      de: 'Meditation ist keine Flucht; es ist eine ruhige Begegnung mit der Realität.',
      es: 'La meditación no es evasión; es un encuentro sereno con la realidad.',
      fr: 'La méditation n\'est pas une évasion; c\'est une rencontre sereine avec la réalité.',
      hi: 'ध्यान भागना नहीं है; यह वास्तविकता के साथ एक शांत मुठभेड़ है।',
      zh: '冥想不是逃避；而是與現實的平靜相遇。',
    },
    originalLanguage: 'en',
    author: 'Thich Nhat Hanh',
    cultureTag: 'contemporary',
    category: 'Practice',
    createdAt: new Date().toISOString(),
  },

  // MORE BUDDHIST - Tibetan Buddhism
  {
    id: 42,
    text: 'ཐུགས་རྗེ་ཆེན་པོ།',
    textTransliteration: 'Thugs rje chen po',
    translations: {
      en: 'Great compassion. Universal loving-kindness.',
      pl: 'Wielkie współczucie. Uniwersalna życzliwość.',
      de: 'Großes Mitgefühl. Universelle Güte.',
      es: 'Gran compasión. Bondad amorosa universal.',
      fr: 'Grande compassion. Bienveillance universelle.',
      hi: 'महान करुणा। सार्वभौमिक प्रेमपूर्ण दयालुता।',
      zh: '大悲心。普世慈愛。',
    },
    originalLanguage: 'bo',
    author: 'Tibetan Buddhist Teaching',
    cultureTag: 'buddhist',
    category: 'Compassion',
    createdAt: new Date().toISOString(),
  },

  // MORE VEDIC
  {
    id: 43,
    text: 'सत्यं वद। धर्मं चर।',
    textTransliteration: 'Satyaṃ vada. Dharmaṃ cara.',
    translations: {
      en: 'Speak the truth. Practice righteousness.',
      pl: 'Mów prawdę. Praktykuj prawość.',
      de: 'Sprich die Wahrheit. Praktiziere Rechtschaffenheit.',
      es: 'Habla la verdad. Practica la rectitud.',
      fr: 'Dis la vérité. Pratique la droiture.',
      hi: 'सत्य बोलो। धर्म का पालन करो।',
      zh: '說真話。行正道。',
    },
    originalLanguage: 'sa',
    author: 'Taittiriya Upanishad',
    cultureTag: 'vedic',
    category: 'Wisdom',
    createdAt: new Date().toISOString(),
  },

  // MORE ZEN
  {
    id: 44,
    text: '行住坐臥',
    textTransliteration: 'Gyō jū za ga',
    translations: {
      en: 'Walking, standing, sitting, lying down - all are meditation.',
      pl: 'Chodzenie, stanie, siedzenie, leżenie - wszystko to medytacja.',
      de: 'Gehen, Stehen, Sitzen, Liegen - alles ist Meditation.',
      es: 'Caminar, estar de pie, sentarse, acostarse - todo es meditación.',
      fr: 'Marcher, se tenir debout, s\'asseoir, se coucher - tout est méditation.',
      hi: 'चलना, खड़ा होना, बैठना, लेटना - सब ध्यान है।',
      zh: '行住坐臥皆是禪。',
    },
    originalLanguage: 'ja',
    author: 'Zen Teaching',
    cultureTag: 'zen',
    category: 'Practice',
    createdAt: new Date().toISOString(),
  },

  // MORE TAOIST
  {
    id: 45,
    text: '靜以修身，儉以養德。',
    textTransliteration: 'Jìng yǐ xiū shēn, jiǎn yǐ yǎng dé.',
    translations: {
      en: 'Through stillness, cultivate the body. Through frugality, nourish virtue.',
      pl: 'Poprzez ciszę kultywuj ciało. Poprzez oszczędność pielęgnuj cnotę.',
      de: 'Durch Stille kultiviere den Körper. Durch Genügsamkeit nähre die Tugend.',
      es: 'A través de la quietud, cultiva el cuerpo. A través de la frugalidad, nutre la virtud.',
      fr: 'Par le calme, cultive le corps. Par la frugalité, nourris la vertu.',
      hi: 'शांति के माध्यम से शरीर को साधो। मितव्ययिता के माध्यम से गुण का पोषण करो।',
      zh: '靜以修身，儉以養德。',
    },
    originalLanguage: 'zh',
    author: 'Zhuge Liang',
    cultureTag: 'taoist',
    category: 'Practice',
    createdAt: new Date().toISOString(),
  },

  // MORE SUFI
  {
    id: 46,
    text: 'آنچه می‌جویی، تو را می‌جوید.',
    textTransliteration: 'An-che mi-juyi, to ra mi-juyad.',
    translations: {
      en: 'What you seek is seeking you.',
      pl: 'To, czego szukasz, szuka ciebie.',
      de: 'Was du suchst, sucht dich.',
      es: 'Lo que buscas te está buscando.',
      fr: 'Ce que tu cherches te cherche.',
      hi: 'जो आप खोज रहे हैं, वह आपको खोज रहा है।',
      zh: '你所尋找的，也在尋找你。',
    },
    originalLanguage: 'fa',
    author: 'Rumi',
    cultureTag: 'sufi',
    category: 'Wisdom',
    createdAt: new Date().toISOString(),
  },

  // MORE STOIC
  {
    id: 47,
    text: 'Hic et nunc.',
    translations: {
      en: 'Here and now.',
      pl: 'Tu i teraz.',
      de: 'Hier und jetzt.',
      es: 'Aquí y ahora.',
      fr: 'Ici et maintenant.',
      hi: 'यहाँ और अभी।',
      zh: '此時此地。',
    },
    originalLanguage: 'la',
    author: 'Stoic Maxim',
    cultureTag: 'stoic',
    category: 'Mindfulness',
    createdAt: new Date().toISOString(),
  },

  // MORE CHRISTIAN CONTEMPLATIVE
  {
    id: 48,
    text: 'Deus caritas est.',
    translations: {
      en: 'God is love.',
      pl: 'Bóg jest miłością.',
      de: 'Gott ist Liebe.',
      es: 'Dios es amor.',
      fr: 'Dieu est amour.',
      hi: 'ईश्वर प्रेम है।',
      zh: '神即是愛。',
    },
    originalLanguage: 'la',
    author: '1 John 4:8',
    cultureTag: 'christian',
    category: 'Love',
    createdAt: new Date().toISOString(),
  },

  // MORE CONTEMPORARY
  {
    id: 49,
    text: 'You can\'t stop the waves, but you can learn to surf.',
    translations: {
      en: 'You can\'t stop the waves, but you can learn to surf.',
      pl: 'Nie możesz zatrzymać fal, ale możesz nauczyć się surfować.',
      de: 'Du kannst die Wellen nicht stoppen, aber du kannst lernen zu surfen.',
      es: 'No puedes detener las olas, pero puedes aprender a surfear.',
      fr: 'Tu ne peux pas arrêter les vagues, mais tu peux apprendre à surfer.',
      hi: 'आप लहरों को नहीं रोक सकते, लेकिन आप सर्फ करना सीख सकते हैं।',
      zh: '你無法阻止波浪，但你可以學會衝浪。',
    },
    originalLanguage: 'en',
    author: 'Jon Kabat-Zinn',
    cultureTag: 'contemporary',
    category: 'Acceptance',
    createdAt: new Date().toISOString(),
  },
  {
    id: 50,
    text: 'In the beginner\'s mind there are many possibilities, but in the expert\'s there are few.',
    translations: {
      en: 'In the beginner\'s mind there are many possibilities, but in the expert\'s there are few.',
      pl: 'W umyśle początkującego jest wiele możliwości, ale w umyśle eksperta jest ich niewiele.',
      de: 'Im Geist des Anfängers gibt es viele Möglichkeiten, aber im Geist des Experten gibt es nur wenige.',
      es: 'En la mente del principiante hay muchas posibilidades, pero en la del experto hay pocas.',
      fr: 'Dans l\'esprit du débutant il y a beaucoup de possibilités, mais dans celui de l\'expert il y en a peu.',
      hi: 'शुरुआती के मन में कई संभावनाएं हैं, लेकिन विशेषज्ञ के मन में कुछ ही हैं।',
      zh: '初心者心中有無限可能，專家心中卻寥寥無幾。',
    },
    originalLanguage: 'en',
    author: 'Shunryu Suzuki',
    cultureTag: 'zen',
    category: 'Wisdom',
    createdAt: new Date().toISOString(),
  },

  // ADDITIONAL BUDDHIST
  {
    id: 51,
    text: 'न हि वेरेन वेरानि सम्मन्तीध कुदाचनं।',
    textTransliteration: 'Na hi verena verāni sammantīdha kudācanaṃ.',
    translations: {
      en: 'Hatred is never appeased by hatred. By non-hatred alone is hatred appeased.',
      pl: 'Nienawiści nigdy nie łagodzi nienawiść. Tylko brak nienawiści łagodzi nienawiść.',
      de: 'Hass wird nie durch Hass beschwichtigt. Nur durch Nicht-Hass wird Hass beschwichtigt.',
      es: 'El odio nunca se apacigua con odio. Solo con la ausencia de odio se apacigua el odio.',
      fr: 'La haine n\'est jamais apaisée par la haine. Seule la non-haine apaise la haine.',
      hi: 'घृणा कभी घृणा से शांत नहीं होती। केवल अघृणा से ही घृणा शांत होती है।',
      zh: '怨恨絕不能以怨恨止息。唯有慈愛能止息怨恨。',
    },
    originalLanguage: 'pi',
    author: 'Buddha (Dhammapada)',
    cultureTag: 'buddhist',
    category: 'Compassion',
    createdAt: new Date().toISOString(),
  },

  // ADDITIONAL VEDIC
  {
    id: 52,
    text: 'ॐ शान्तिः शान्तिः शान्तिः।',
    textTransliteration: 'Oṃ śāntiḥ śāntiḥ śāntiḥ.',
    translations: {
      en: 'Om, peace, peace, peace.',
      pl: 'Om, pokój, pokój, pokój.',
      de: 'Om, Frieden, Frieden, Frieden.',
      es: 'Om, paz, paz, paz.',
      fr: 'Om, paix, paix, paix.',
      hi: 'ॐ शान्ति, शान्ति, शान्ति।',
      zh: '唵，和平，和平，和平。',
    },
    originalLanguage: 'sa',
    author: 'Vedic Mantra',
    cultureTag: 'vedic',
    category: 'Inner Peace',
    createdAt: new Date().toISOString(),
  },

  // ADDITIONAL ZEN
  {
    id: 53,
    text: '一期一会',
    textTransliteration: 'Ichi-go ichi-e',
    translations: {
      en: 'One time, one meeting. This moment will never come again.',
      pl: 'Jeden raz, jedno spotkanie. Ta chwila nigdy się nie powtórzy.',
      de: 'Einmal, ein Treffen. Dieser Moment wird nie wiederkommen.',
      es: 'Una vez, un encuentro. Este momento nunca volverá.',
      fr: 'Une fois, une rencontre. Ce moment ne reviendra jamais.',
      hi: 'एक बार, एक मुलाकात। यह क्षण फिर कभी नहीं आएगा।',
      zh: '一期一會。此刻永不再來。',
    },
    originalLanguage: 'ja',
    author: 'Zen Teaching',
    cultureTag: 'zen',
    category: 'Mindfulness',
    createdAt: new Date().toISOString(),
  },

  // ADDITIONAL TAOIST
  {
    id: 54,
    text: '大音希聲，大象無形。',
    textTransliteration: 'Dà yīn xī shēng, dà xiàng wú xíng.',
    translations: {
      en: 'The greatest sound is unhearable. The greatest form is formless.',
      pl: 'Największy dźwięk jest niesłyszalny. Największa forma jest bezforemna.',
      de: 'Der größte Klang ist unhörbar. Die größte Form ist formlos.',
      es: 'El mayor sonido es inaudible. La mayor forma es sin forma.',
      fr: 'Le plus grand son est inaudible. La plus grande forme est sans forme.',
      hi: 'सबसे बड़ी ध्वनि अश्रव्य है। सबसे बड़ा रूप निराकार है।',
      zh: '大音希聲，大象無形。',
    },
    originalLanguage: 'zh',
    author: 'Lao Tzu (Tao Te Ching 41)',
    cultureTag: 'taoist',
    category: 'Wisdom',
    createdAt: new Date().toISOString(),
  },

  // ADDITIONAL SUFI
  {
    id: 55,
    text: 'عشق آتشی است که چون بزند، هر چه نیست بسوزد.',
    textTransliteration: 'Eshq atashi ast ke chun bezanad, har-che nist besuzad.',
    translations: {
      en: 'Love is a fire that when it blazes, burns away everything that is not love.',
      pl: 'Miłość jest ogniem, który gdy płonie, spala wszystko, co nie jest miłością.',
      de: 'Liebe ist ein Feuer, das, wenn es lodert, alles verbrennt, was nicht Liebe ist.',
      es: 'El amor es un fuego que cuando arde, quema todo lo que no es amor.',
      fr: 'L\'amour est un feu qui, lorsqu\'il flambe, brûle tout ce qui n\'est pas amour.',
      hi: 'प्रेम एक अग्नि है जो जब धधकती है, तो वह सब जला देती है जो प्रेम नहीं है।',
      zh: '愛是一把火，當它燃燒時，焚盡一切非愛之物。',
    },
    originalLanguage: 'fa',
    author: 'Rumi',
    cultureTag: 'sufi',
    category: 'Love',
    createdAt: new Date().toISOString(),
  },

  // ADDITIONAL STOIC
  {
    id: 56,
    text: 'Tempus fugit.',
    translations: {
      en: 'Time flies. Time flees.',
      pl: 'Czas ucieka.',
      de: 'Die Zeit flieht.',
      es: 'El tiempo vuela.',
      fr: 'Le temps fuit.',
      hi: 'समय उड़ जाता है।',
      zh: '時光飛逝。',
    },
    originalLanguage: 'la',
    author: 'Virgil',
    cultureTag: 'stoic',
    category: 'Mindfulness',
    createdAt: new Date().toISOString(),
  },

  // ADDITIONAL CHRISTIAN CONTEMPLATIVE
  {
    id: 57,
    text: 'Nada te turbe, nada te espante.',
    translations: {
      en: 'Let nothing disturb you, let nothing frighten you.',
      pl: 'Niech nic cię nie niepokoi, niech nic cię nie przeraża.',
      de: 'Lass dich von nichts beunruhigen, lass dich von nichts erschrecken.',
      es: 'Nada te turbe, nada te espante.',
      fr: 'Que rien ne te trouble, que rien ne t\'effraie.',
      hi: 'कुछ भी आपको परेशान न करे, कुछ भी आपको डराए नहीं।',
      zh: '無事擾你，無事驚你。',
    },
    originalLanguage: 'es',
    author: 'Teresa of Avila',
    cultureTag: 'christian',
    category: 'Inner Peace',
    createdAt: new Date().toISOString(),
  },

  // ADDITIONAL CONTEMPORARY
  {
    id: 58,
    text: 'The quieter you become, the more you can hear.',
    translations: {
      en: 'The quieter you become, the more you can hear.',
      pl: 'Im bardziej stajsz się cichy, tym więcej możesz usłyszeć.',
      de: 'Je stiller du wirst, desto mehr kannst du hören.',
      es: 'Cuanto más tranquilo te vuelves, más puedes oír.',
      fr: 'Plus tu deviens silencieux, plus tu peux entendre.',
      hi: 'जितने शांत आप बनते हैं, उतना अधिक आप सुन सकते हैं।',
      zh: '你越安靜，就越能聽見。',
    },
    originalLanguage: 'en',
    author: 'Ram Dass',
    cultureTag: 'contemporary',
    category: 'Stillness',
    createdAt: new Date().toISOString(),
  },

  // NATIVE AMERICAN WISDOM
  {
    id: 59,
    text: 'We do not inherit the Earth from our ancestors; we borrow it from our children.',
    translations: {
      en: 'We do not inherit the Earth from our ancestors; we borrow it from our children.',
      pl: 'Nie dziedziczymy Ziemi po naszych przodkach; pożyczamy ją od naszych dzieci.',
      de: 'Wir erben die Erde nicht von unseren Vorfahren; wir leihen sie von unseren Kindern.',
      es: 'No heredamos la Tierra de nuestros antepasados; la tomamos prestada de nuestros hijos.',
      fr: 'Nous n\'héritons pas de la Terre de nos ancêtres; nous l\'empruntons à nos enfants.',
      hi: 'हम अपने पूर्वजों से पृथ्वी विरासत में नहीं पाते; हम इसे अपने बच्चों से उधार लेते हैं।',
      zh: '我們不是從祖先那裡繼承地球；我們是從子孫那裡借來的。',
    },
    originalLanguage: 'en',
    author: 'Native American Proverb',
    cultureTag: 'indigenous',
    category: 'Wisdom',
    createdAt: new Date().toISOString(),
  },
  {
    id: 60,
    text: 'Listen to the wind, it talks. Listen to the silence, it speaks. Listen to your heart, it knows.',
    translations: {
      en: 'Listen to the wind, it talks. Listen to the silence, it speaks. Listen to your heart, it knows.',
      pl: 'Słuchaj wiatru, on mówi. Słuchaj ciszy, ona przemawia. Słuchaj swojego serca, ono wie.',
      de: 'Höre dem Wind zu, er spricht. Höre der Stille zu, sie spricht. Höre deinem Herzen zu, es weiß.',
      es: 'Escucha el viento, habla. Escucha el silencio, habla. Escucha tu corazón, sabe.',
      fr: 'Écoute le vent, il parle. Écoute le silence, il parle. Écoute ton cœur, il sait.',
      hi: 'हवा को सुनो, वह बोलती है। मौन को सुनो, वह बोलता है। अपने दिल को सुनो, वह जानता है।',
      zh: '聽風，它在說話。聽沉默，它在訴說。聽你的心，它知道。',
    },
    originalLanguage: 'en',
    author: 'Native American Wisdom',
    cultureTag: 'indigenous',
    category: 'Mindfulness',
    createdAt: new Date().toISOString(),
  },
  {
    id: 61,
    text: 'All things are connected. Whatever befalls the Earth befalls the children of the Earth.',
    translations: {
      en: 'All things are connected. Whatever befalls the Earth befalls the children of the Earth.',
      pl: 'Wszystko jest połączone. Cokolwiek spotyka Ziemię, spotyka dzieci Ziemi.',
      de: 'Alles ist verbunden. Was der Erde widerfährt, widerfährt den Kindern der Erde.',
      es: 'Todo está conectado. Lo que le sucede a la Tierra les sucede a los hijos de la Tierra.',
      fr: 'Tout est connecté. Ce qui arrive à la Terre arrive aux enfants de la Terre.',
      hi: 'सब कुछ जुड़ा हुआ है। जो पृथ्वी पर घटित होता है, वह पृथ्वी के बच्चों पर भी घटित होता है।',
      zh: '萬物相連。降臨於地球的，也降臨於地球之子。',
    },
    originalLanguage: 'en',
    author: 'Chief Seattle',
    cultureTag: 'indigenous',
    category: 'Interconnection',
    createdAt: new Date().toISOString(),
  },
  {
    id: 62,
    text: 'The soul would have no rainbow if the eyes had no tears.',
    translations: {
      en: 'The soul would have no rainbow if the eyes had no tears.',
      pl: 'Dusza nie miałaby tęczy, gdyby oczy nie miały łez.',
      de: 'Die Seele hätte keinen Regenbogen, wenn die Augen keine Tränen hätten.',
      es: 'El alma no tendría arcoíris si los ojos no tuvieran lágrimas.',
      fr: 'L\'âme n\'aurait pas d\'arc-en-ciel si les yeux n\'avaient pas de larmes.',
      hi: 'यदि आंखों में आंसू न होते, तो आत्मा में इंद्रधनुष न होता।',
      zh: '若眼中無淚，靈魂便無彩虹。',
    },
    originalLanguage: 'en',
    author: 'Minquass (Native American)',
    cultureTag: 'indigenous',
    category: 'Wisdom',
    createdAt: new Date().toISOString(),
  },

  // MORE BUDDHIST/VIPASSANA WISDOM
  {
    id: 63,
    text: 'यत्र यत्र मनो याति तत्र तत्र समाधयः।',
    textTransliteration: 'Yatra yatra mano yāti tatra tatra samādhayaḥ.',
    translations: {
      en: 'Wherever the mind goes, there concentration follows.',
      pl: 'Dokądkolwiek idzie umysł, tam podąża koncentracja.',
      de: 'Wohin auch immer der Geist geht, dort folgt die Konzentration.',
      es: 'Dondequiera que vaya la mente, allí sigue la concentración.',
      fr: 'Où que l\'esprit aille, la concentration y suit.',
      hi: 'मन जहां भी जाता है, वहां समाधि अनुसरण करती है।',
      zh: '心去何處，定隨其後。',
    },
    originalLanguage: 'sa',
    author: 'Buddhist Teaching',
    cultureTag: 'vipassana',
    category: 'Concentration',
    createdAt: new Date().toISOString(),
  },
  {
    id: 64,
    text: 'अनित्ये नित्यसंज्ञा च दुःखे सुखसंज्ञा च।',
    textTransliteration: 'Anitye nityasaṃjñā ca duḥkhe sukhasaṃjñā ca.',
    translations: {
      en: 'Perceiving the impermanent as permanent, perceiving suffering as happiness.',
      pl: 'Postrzeganie tego, co nietrwałe, jako trwałe, postrzeganie cierpienia jako szczęścia.',
      de: 'Das Vergängliche als beständig wahrnehmen, das Leiden als Glück wahrnehmen.',
      es: 'Percibir lo impermanente como permanente, percibir el sufrimiento como felicidad.',
      fr: 'Percevoir l\'impermanent comme permanent, percevoir la souffrance comme bonheur.',
      hi: 'अनित्य को नित्य मानना, दुःख को सुख मानना।',
      zh: '視無常為常，視苦為樂。',
    },
    originalLanguage: 'sa',
    author: 'Buddhist Text',
    cultureTag: 'vipassana',
    category: 'Insight',
    createdAt: new Date().toISOString(),
  },
  {
    id: 65,
    text: 'The mind is everything. What you think, you become.',
    translations: {
      en: 'The mind is everything. What you think, you become.',
      pl: 'Umysł jest wszystkim. Czym myślisz, tym się stajesz.',
      de: 'Der Geist ist alles. Was du denkst, wirst du.',
      es: 'La mente lo es todo. Lo que piensas, te conviertes.',
      fr: 'L\'esprit est tout. Ce que tu penses, tu le deviens.',
      hi: 'मन ही सब कुछ है। जो आप सोचते हैं, वही बनते हैं।',
      zh: '心即一切。所思即所成。',
    },
    originalLanguage: 'en',
    author: 'Buddha',
    cultureTag: 'buddhist',
    category: 'Mind',
    createdAt: new Date().toISOString(),
  },

  // MORE CONTEMPORARY MEDITATION TEACHERS
  {
    id: 66,
    text: 'Meditation is not about stopping thoughts, but recognizing that we are more than our thoughts and our feelings.',
    translations: {
      en: 'Meditation is not about stopping thoughts, but recognizing that we are more than our thoughts and our feelings.',
      pl: 'Medytacja nie polega na zatrzymywaniu myśli, ale na rozpoznaniu, że jesteśmy czymś więcej niż naszymi myślami i uczuciami.',
      de: 'Meditation geht nicht darum, Gedanken zu stoppen, sondern zu erkennen, dass wir mehr sind als unsere Gedanken und Gefühle.',
      es: 'La meditación no se trata de detener los pensamientos, sino de reconocer que somos más que nuestros pensamientos y sentimientos.',
      fr: 'La méditation ne consiste pas à arrêter les pensées, mais à reconnaître que nous sommes plus que nos pensées et nos sentiments.',
      hi: 'ध्यान विचारों को रोकने के बारे में नहीं है, बल्कि यह पहचानने के बारे में है कि हम अपने विचारों और भावनाओं से अधिक हैं।',
      zh: '冥想不是要停止思想，而是認識到我們不僅僅是我們的思想和感受。',
    },
    originalLanguage: 'en',
    author: 'Arianna Huffington',
    cultureTag: 'contemporary',
    category: 'Practice',
    createdAt: new Date().toISOString(),
  },
  {
    id: 67,
    text: 'Mindfulness isn\'t difficult. We just need to remember to do it.',
    translations: {
      en: 'Mindfulness isn\'t difficult. We just need to remember to do it.',
      pl: 'Uważność nie jest trudna. Musimy tylko pamiętać, aby być uważni.',
      de: 'Achtsamkeit ist nicht schwierig. Wir müssen uns nur daran erinnern, sie zu praktizieren.',
      es: 'La atención plena no es difícil. Solo necesitamos recordar practicarla.',
      fr: 'La pleine conscience n\'est pas difficile. Il suffit de se rappeler de la pratiquer.',
      hi: 'सावधानी कठिन नहीं है। हमें बस इसे करने की याद रखनी है।',
      zh: '正念並不難。我們只需記得去做。',
    },
    originalLanguage: 'en',
    author: 'Sharon Salzberg',
    cultureTag: 'contemporary',
    category: 'Mindfulness',
    createdAt: new Date().toISOString(),
  },
  {
    id: 68,
    text: 'The best way to capture moments is to pay attention. This is how we cultivate mindfulness.',
    translations: {
      en: 'The best way to capture moments is to pay attention. This is how we cultivate mindfulness.',
      pl: 'Najlepszy sposób na uchwycenie chwil to zwrócenie uwagi. W ten sposób kultywujemy uważność.',
      de: 'Der beste Weg, Momente festzuhalten, ist aufmerksam zu sein. So kultivieren wir Achtsamkeit.',
      es: 'La mejor manera de capturar momentos es prestar atención. Así es como cultivamos la atención plena.',
      fr: 'La meilleure façon de capturer des moments est de faire attention. C\'est ainsi que nous cultivons la pleine conscience.',
      hi: 'क्षणों को कैप्चर करने का सबसे अच्छा तरीका ध्यान देना है। इस तरह हम सावधानी विकसित करते हैं।',
      zh: '捕捉時刻的最佳方式是關注。這就是我們培養正念的方式。',
    },
    originalLanguage: 'en',
    author: 'Jon Kabat-Zinn',
    cultureTag: 'contemporary',
    category: 'Mindfulness',
    createdAt: new Date().toISOString(),
  },

  // MORE STOIC WISDOM
  {
    id: 69,
    text: 'Ἔνδον σκάπτε· ἔνδον ἡ πηγὴ τοῦ ἀγαθοῦ.',
    textTransliteration: 'Éndon skápte: éndon hē pēgḗ toû agathoû.',
    translations: {
      en: 'Dig within. Within is the fountain of good.',
      pl: 'Kop w sobie. Wewnątrz jest źródło dobra.',
      de: 'Grabe in dir. Drinnen ist die Quelle des Guten.',
      es: 'Cava dentro. Dentro está la fuente del bien.',
      fr: 'Creuse en toi. À l\'intérieur se trouve la source du bien.',
      hi: 'भीतर खोदो। भीतर अच्छाई का स्रोत है।',
      zh: '內求。內中有善之泉源。',
    },
    originalLanguage: 'grc',
    author: 'Marcus Aurelius',
    cultureTag: 'stoic',
    category: 'Self-Knowledge',
    createdAt: new Date().toISOString(),
  },
  {
    id: 70,
    text: 'Ὁ βίος βραχύς, ἡ δὲ τέχνη μακρή.',
    textTransliteration: 'Ho bíos brakhús, hē dè tékhnē makrḗ.',
    translations: {
      en: 'Life is short, but the art is long.',
      pl: 'Życie jest krótkie, ale sztuka długa.',
      de: 'Das Leben ist kurz, aber die Kunst ist lang.',
      es: 'La vida es corta, pero el arte es largo.',
      fr: 'La vie est courte, mais l\'art est long.',
      hi: 'जीवन छोटा है, लेकिन कला लंबी है।',
      zh: '生命短暫，技藝悠長。',
    },
    originalLanguage: 'grc',
    author: 'Hippocrates',
    cultureTag: 'stoic',
    category: 'Wisdom',
    createdAt: new Date().toISOString(),
  },

  // OCCASION-SPECIFIC: ANXIETY
  {
    id: 71,
    text: 'Anxiety is the dizziness of freedom.',
    translations: {
      en: 'Anxiety is the dizziness of freedom.',
      pl: 'Lęk to zawrót głowy wolności.',
      de: 'Angst ist der Schwindel der Freiheit.',
      es: 'La ansiedad es el vértigo de la libertad.',
      fr: 'L\'anxiété est le vertige de la liberté.',
      hi: 'चिंता स्वतंत्रता का चक्कर है।',
      zh: '焦慮是自由的眩暈。',
    },
    originalLanguage: 'en',
    author: 'Søren Kierkegaard',
    cultureTag: 'occasion_anxiety',
    category: 'Anxiety',
    createdAt: new Date().toISOString(),
  },
  {
    id: 72,
    text: 'You don\'t have to control your thoughts. You just have to stop letting them control you.',
    translations: {
      en: 'You don\'t have to control your thoughts. You just have to stop letting them control you.',
      pl: 'Nie musisz kontrolować swoich myśli. Musisz tylko przestać pozwalać im kontrolować ciebie.',
      de: 'Du musst deine Gedanken nicht kontrollieren. Du musst nur aufhören, sie dich kontrollieren zu lassen.',
      es: 'No tienes que controlar tus pensamientos. Solo tienes que dejar de permitir que te controlen.',
      fr: 'Tu n\'as pas besoin de contrôler tes pensées. Tu dois juste arrêter de les laisser te contrôler.',
      hi: 'आपको अपने विचारों को नियंत्रित करने की आवश्यकता नहीं है। आपको बस उन्हें आपको नियंत्रित करने से रोकना है।',
      zh: '你不必控制你的思想。你只需停止讓它們控制你。',
    },
    originalLanguage: 'en',
    author: 'Dan Millman',
    cultureTag: 'occasion_anxiety',
    category: 'Anxiety',
    createdAt: new Date().toISOString(),
  },

  // OCCASION-SPECIFIC: FOCUS
  {
    id: 73,
    text: 'Concentration is the secret of strength.',
    translations: {
      en: 'Concentration is the secret of strength.',
      pl: 'Koncentracja jest sekretem siły.',
      de: 'Konzentration ist das Geheimnis der Stärke.',
      es: 'La concentración es el secreto de la fuerza.',
      fr: 'La concentration est le secret de la force.',
      hi: 'एकाग्रता शक्ति का रहस्य है।',
      zh: '專注是力量的秘密。',
    },
    originalLanguage: 'en',
    author: 'Ralph Waldo Emerson',
    cultureTag: 'occasion_focus',
    category: 'Focus',
    createdAt: new Date().toISOString(),
  },

  // MORE ZEN
  {
    id: 74,
    text: '一期一会',
    textTransliteration: 'Ichi-go ichi-e',
    translations: {
      en: 'One time, one meeting. Treasure every encounter, for it will never recur.',
      pl: 'Jeden raz, jedno spotkanie. Cenne każde spotkanie, bo nigdy się nie powtórzy.',
      de: 'Einmal, ein Treffen. Schätze jede Begegnung, denn sie wird sich nie wiederholen.',
      es: 'Una vez, un encuentro. Atesora cada encuentro, porque nunca se repetirá.',
      fr: 'Une fois, une rencontre. Chéris chaque rencontre, car elle ne se reproduira jamais.',
      hi: 'एक बार, एक मुलाकात। हर मुलाकात को संजोएं, क्योंकि यह फिर कभी नहीं होगी।',
      zh: '一期一會。珍惜每次相遇，因為它不會再現。',
    },
    originalLanguage: 'ja',
    author: 'Japanese Zen Teaching',
    cultureTag: 'zen',
    category: 'Mindfulness',
    createdAt: new Date().toISOString(),
  },
];

export const MOCK_SESSIONS: MeditationSession[] = [
  // TRADITIONAL BEGINNER SESSIONS (Level 1)
  {
    id: 1,
    title: 'Morning Awakening',
    titleKey: 'sessionsList.morningAwakening.title',
    description: 'Start your day with clarity and focus. A gentle 5-minute practice to center yourself.',
    descriptionKey: 'sessionsList.morningAwakening.description',
    languageCode: 'en',
    durationSeconds: 300, // 5 minutes
    level: 1,
    cultureTag: 'traditional',
    instructionId: 'morning_energy', // Morning energizing instruction
    ambientFrequency: 432,
    chimeFrequency: 528,
    createdAt: new Date().toISOString(),
  },
  {
    id: 2,
    title: 'Breath Awareness',
    titleKey: 'sessionsList.breathAwareness.title',
    description: 'Focus on your natural breath. A foundational practice for beginners.',
    descriptionKey: 'sessionsList.breathAwareness.description',
    languageCode: 'en',
    durationSeconds: 600, // 10 minutes
    level: 1,
    cultureTag: 'traditional',
    instructionId: 'level1_breath', // Pre-session breathing instruction
    ambientFrequency: 432,
    chimeFrequency: 528,
    createdAt: new Date().toISOString(),
  },
  {
    id: 3,
    title: 'Body Scan Relaxation',
    titleKey: 'sessionsList.bodyScanRelaxation.title',
    description: 'Progressive relaxation technique moving attention through the body.',
    descriptionKey: 'sessionsList.bodyScanRelaxation.description',
    languageCode: 'en',
    durationSeconds: 900, // 15 minutes
    level: 2,
    cultureTag: 'traditional',
    instructionId: 'level1_body_scan', // Pre-session body scan instruction
    ambientFrequency: 432,
    chimeFrequency: 528,
    createdAt: new Date().toISOString(),
  },
  {
    id: 4,
    title: 'Loving Kindness',
    titleKey: 'sessionsList.lovingKindness.title',
    description: 'Cultivate compassion and goodwill toward yourself and others.',
    descriptionKey: 'sessionsList.lovingKindness.description',
    languageCode: 'en',
    durationSeconds: 720, // 12 minutes
    level: 2,
    cultureTag: 'traditional',
    instructionId: 'level3_loving_kindness', // Loving-kindness meditation instruction
    ambientFrequency: 528,
    chimeFrequency: 528,
    createdAt: new Date().toISOString(),
  },
  {
    id: 5,
    title: 'Deep Meditation',
    titleKey: 'sessionsList.deepMeditation.title',
    description: 'Extended practice for experienced meditators. Dive into stillness.',
    descriptionKey: 'sessionsList.deepMeditation.description',
    languageCode: 'en',
    durationSeconds: 1200, // 20 minutes
    level: 3,
    cultureTag: 'traditional',
    instructionId: 'level3_mindfulness', // Deep meditation instruction
    ambientFrequency: 432,
    chimeFrequency: 528,
    createdAt: new Date().toISOString(),
  },

  // OCCASION-SPECIFIC SESSIONS
  // Morning Energy
  {
    id: 10,
    title: 'Morning Energy Boost',
    titleKey: 'sessionsList.morningEnergyBoost.title',
    description: 'Energize your body and mind for the day ahead with breath techniques.',
    descriptionKey: 'sessionsList.morningEnergyBoost.description',
    languageCode: 'en',
    durationSeconds: 480, // 8 minutes
    level: 1,
    cultureTag: 'occasion_morning',
    instructionId: 'morning_energy', // Morning energizing instruction
    ambientFrequency: 432,
    chimeFrequency: 528,
    createdAt: new Date().toISOString(),
  },
  {
    id: 11,
    title: 'Sunrise Meditation',
    titleKey: 'sessionsList.sunriseMeditation.title',
    description: 'Greet the new day with gratitude and intention setting.',
    descriptionKey: 'sessionsList.sunriseMeditation.description',
    languageCode: 'en',
    durationSeconds: 600, // 10 minutes
    level: 2,
    cultureTag: 'occasion_morning',
    instructionId: 'gratitude_practice', // Morning gratitude and intention
    ambientFrequency: 432,
    chimeFrequency: 528,
    createdAt: new Date().toISOString(),
  },

  // Stress Relief
  {
    id: 20,
    title: 'Quick Stress Relief',
    titleKey: 'sessionsList.quickStressRelief.title',
    description: 'Release tension in just 5 minutes. Perfect for work breaks.',
    descriptionKey: 'sessionsList.quickStressRelief.description',
    languageCode: 'en',
    durationSeconds: 300, // 5 minutes
    level: 1,
    cultureTag: 'occasion_stress',
    instructionId: 'stress_relief', // Stress relief instruction
    ambientFrequency: 432,
    chimeFrequency: 528,
    createdAt: new Date().toISOString(),
  },
  {
    id: 21,
    title: 'Deep Stress Release',
    titleKey: 'sessionsList.deepStressRelease.title',
    description: 'Comprehensive stress relief through progressive relaxation.',
    descriptionKey: 'sessionsList.deepStressRelease.description',
    languageCode: 'en',
    durationSeconds: 900, // 15 minutes
    level: 2,
    cultureTag: 'occasion_stress',
    instructionId: 'stress_relief', // Stress relief instruction
    ambientFrequency: 432,
    chimeFrequency: 528,
    createdAt: new Date().toISOString(),
  },

  // Sleep Preparation
  {
    id: 30,
    title: 'Evening Wind Down',
    titleKey: 'sessionsList.eveningWindDown.title',
    description: 'Release the day\'s tensions and prepare for restful sleep.',
    descriptionKey: 'sessionsList.eveningWindDown.description',
    languageCode: 'en',
    durationSeconds: 480, // 8 minutes
    level: 1,
    cultureTag: 'occasion_sleep',
    instructionId: 'sleep_preparation', // Sleep preparation instruction
    ambientFrequency: 432,
    chimeFrequency: 528,
    createdAt: new Date().toISOString(),
  },
  {
    id: 31,
    title: 'Sleep Sanctuary',
    titleKey: 'sessionsList.sleepSanctuary.title',
    description: 'Deep body scan and relaxation for profound rest.',
    descriptionKey: 'sessionsList.sleepSanctuary.description',
    languageCode: 'en',
    durationSeconds: 1200, // 20 minutes
    level: 2,
    cultureTag: 'occasion_sleep',
    instructionId: 'sleep_preparation', // Sleep preparation instruction
    ambientFrequency: 432,
    chimeFrequency: 528,
    createdAt: new Date().toISOString(),
  },

  // Deep Focus
  {
    id: 40,
    title: 'Concentration Builder',
    titleKey: 'sessionsList.concentrationBuilder.title',
    description: 'Sharpen your focus and eliminate distractions.',
    descriptionKey: 'sessionsList.concentrationBuilder.description',
    languageCode: 'en',
    durationSeconds: 600, // 10 minutes
    level: 2,
    cultureTag: 'occasion_focus',
    instructionId: 'level2_breath_counting', // Focus through breath counting
    ambientFrequency: 432,
    chimeFrequency: 528,
    createdAt: new Date().toISOString(),
  },
  {
    id: 41,
    title: 'Flow State Activation',
    titleKey: 'sessionsList.flowStateActivation.title',
    description: 'Enter deep concentration for work or study.',
    descriptionKey: 'sessionsList.flowStateActivation.description',
    languageCode: 'en',
    durationSeconds: 900, // 15 minutes
    level: 3,
    cultureTag: 'occasion_focus',
    instructionId: 'level4_open_awareness', // Flow state through open awareness
    ambientFrequency: 432,
    chimeFrequency: 528,
    createdAt: new Date().toISOString(),
  },

  // Anxiety Release
  {
    id: 50,
    title: 'Calm Anxiety',
    titleKey: 'sessionsList.calmAnxiety.title',
    description: 'Soothe anxious thoughts with gentle breath awareness.',
    descriptionKey: 'sessionsList.calmAnxiety.description',
    languageCode: 'en',
    durationSeconds: 420, // 7 minutes
    level: 1,
    cultureTag: 'occasion_anxiety',
    instructionId: 'anxiety_calm', // Anxiety calming instruction
    ambientFrequency: 432,
    chimeFrequency: 528,
    createdAt: new Date().toISOString(),
  },
  {
    id: 51,
    title: 'Anxiety Release Practice',
    titleKey: 'sessionsList.anxietyReleasePractice.title',
    description: 'Ground yourself and release worry through body awareness.',
    descriptionKey: 'sessionsList.anxietyReleasePractice.description',
    languageCode: 'en',
    durationSeconds: 720, // 12 minutes
    level: 2,
    cultureTag: 'occasion_anxiety',
    instructionId: 'anxiety_calm', // Anxiety calming instruction
    ambientFrequency: 432,
    chimeFrequency: 528,
    createdAt: new Date().toISOString(),
  },

  // Grief & Loss
  {
    id: 60,
    title: 'Healing Through Grief',
    titleKey: 'sessionsList.healingThroughGrief.title',
    description: 'A gentle space to honor loss and find peace.',
    descriptionKey: 'sessionsList.healingThroughGrief.description',
    languageCode: 'en',
    durationSeconds: 900, // 15 minutes
    level: 2,
    cultureTag: 'occasion_grief',
    instructionId: 'level3_loving_kindness', // Compassionate meditation for grief
    ambientFrequency: 528, // Healing frequency
    chimeFrequency: 528,
    createdAt: new Date().toISOString(),
  },
  {
    id: 61,
    title: 'Embracing Loss',
    titleKey: 'sessionsList.embracingLoss.title',
    description: 'Compassionate meditation for processing difficult emotions.',
    descriptionKey: 'sessionsList.embracingLoss.description',
    languageCode: 'en',
    durationSeconds: 1200, // 20 minutes
    level: 3,
    cultureTag: 'occasion_grief',
    instructionId: 'level3_loving_kindness', // Compassionate meditation for grief
    ambientFrequency: 528,
    chimeFrequency: 528,
    createdAt: new Date().toISOString(),
  },

  // Gratitude Practice
  {
    id: 70,
    title: 'Gratitude Reflection',
    titleKey: 'sessionsList.gratitudeReflection.title',
    description: 'Cultivate appreciation for life\'s blessings.',
    descriptionKey: 'sessionsList.gratitudeReflection.description',
    languageCode: 'en',
    durationSeconds: 480, // 8 minutes
    level: 1,
    cultureTag: 'occasion_gratitude',
    instructionId: 'gratitude_practice', // Gratitude meditation instruction
    ambientFrequency: 528,
    chimeFrequency: 528,
    createdAt: new Date().toISOString(),
  },
  {
    id: 71,
    title: 'Deep Gratitude Journey',
    titleKey: 'sessionsList.deepGratitudeJourney.title',
    description: 'Explore profound thankfulness and joy.',
    descriptionKey: 'sessionsList.deepGratitudeJourney.description',
    languageCode: 'en',
    durationSeconds: 900, // 15 minutes
    level: 2,
    cultureTag: 'occasion_gratitude',
    instructionId: 'gratitude_practice', // Gratitude meditation instruction
    ambientFrequency: 528,
    chimeFrequency: 528,
    createdAt: new Date().toISOString(),
  },

  // Creative Inspiration
  {
    id: 80,
    title: 'Creative Awakening',
    titleKey: 'sessionsList.creativeAwakening.title',
    description: 'Unlock your creative potential through open awareness.',
    descriptionKey: 'sessionsList.creativeAwakening.description',
    languageCode: 'en',
    durationSeconds: 600, // 10 minutes
    level: 2,
    cultureTag: 'occasion_creativity',
    instructionId: 'level4_open_awareness', // Open awareness for creativity
    ambientFrequency: 432,
    chimeFrequency: 528,
    createdAt: new Date().toISOString(),
  },
  {
    id: 81,
    title: 'Inspiration Flow',
    titleKey: 'sessionsList.inspirationFlow.title',
    description: 'Access your inner muse and creative genius.',
    descriptionKey: 'sessionsList.inspirationFlow.description',
    languageCode: 'en',
    durationSeconds: 900, // 15 minutes
    level: 3,
    cultureTag: 'occasion_creativity',
    instructionId: 'level4_open_awareness', // Open awareness for creativity
    ambientFrequency: 432,
    chimeFrequency: 528,
    createdAt: new Date().toISOString(),
  },

  // CULTURALLY DIVERSE MEDITATION SESSIONS
  // Zen (Japanese)
  {
    id: 100,
    title: 'Zazen - Zen Sitting',
    titleKey: 'sessionsList.zazenZenSitting.title',
    description: 'Traditional Zen meditation. Just sitting, observing breath and thoughts.',
    descriptionKey: 'sessionsList.zazenZenSitting.description',
    languageCode: 'en',
    durationSeconds: 1200, // 20 minutes
    level: 3,
    cultureTag: 'zen',
    instructionId: 'zen_zazen', // Zen sitting meditation instruction
    ambientFrequency: 432,
    chimeFrequency: 528,
    createdAt: new Date().toISOString(),
  },
  {
    id: 101,
    title: 'Kinhin - Zen Walking',
    titleKey: 'sessionsList.kinhinZenWalking.title',
    description: 'Slow, mindful walking between sitting periods.',
    descriptionKey: 'sessionsList.kinhinZenWalking.description',
    languageCode: 'en',
    durationSeconds: 600, // 10 minutes
    level: 2,
    cultureTag: 'zen',
    instructionId: 'zen_zazen', // Zen walking meditation instruction
    ambientFrequency: 432,
    chimeFrequency: 528,
    createdAt: new Date().toISOString(),
  },
  {
    id: 102,
    title: 'Beginner Zazen',
    titleKey: 'sessionsList.beginnerZazen.title',
    description: 'Introduction to Zen sitting meditation practice.',
    descriptionKey: 'sessionsList.beginnerZazen.description',
    languageCode: 'en',
    durationSeconds: 600, // 10 minutes
    level: 1,
    cultureTag: 'zen',
    instructionId: 'zen_zazen', // Zen sitting meditation instruction (beginner-friendly)
    ambientFrequency: 432,
    chimeFrequency: 528,
    createdAt: new Date().toISOString(),
  },

  // Vipassana (Buddhist)
  {
    id: 110,
    title: 'Vipassana Body Scan',
    titleKey: 'sessionsList.vipassanaBodyScan.title',
    description: 'Systematic awareness of sensations throughout the body.',
    descriptionKey: 'sessionsList.vipassanaBodyScan.description',
    languageCode: 'en',
    durationSeconds: 1800, // 30 minutes
    level: 4,
    cultureTag: 'vipassana',
    instructionId: 'level4_vipassana_scan', // Advanced Vipassana body scanning instruction
    ambientFrequency: 432,
    chimeFrequency: 528,
    createdAt: new Date().toISOString(),
  },
  {
    id: 111,
    title: 'Insight Meditation',
    titleKey: 'sessionsList.insightMeditation.title',
    description: 'Observe the impermanent nature of all phenomena.',
    descriptionKey: 'sessionsList.insightMeditation.description',
    languageCode: 'en',
    durationSeconds: 1200, // 20 minutes
    level: 3,
    cultureTag: 'vipassana',
    instructionId: 'level3_mindfulness', // Intermediate mindfulness/insight instruction
    ambientFrequency: 432,
    chimeFrequency: 528,
    createdAt: new Date().toISOString(),
  },
  {
    id: 112,
    title: 'Beginner Vipassana',
    titleKey: 'sessionsList.beginnerVipassana.title',
    description: 'Introduction to insight meditation practice.',
    descriptionKey: 'sessionsList.beginnerVipassana.description',
    languageCode: 'en',
    durationSeconds: 900, // 15 minutes
    level: 2,
    cultureTag: 'vipassana',
    instructionId: 'level2_breath_counting', // Intermediate breath awareness instruction
    ambientFrequency: 432,
    chimeFrequency: 528,
    createdAt: new Date().toISOString(),
  },

  // Vedic (Hindu)
  {
    id: 120,
    title: 'Om Meditation',
    titleKey: 'sessionsList.omMeditation.title',
    description: 'Chant and meditate on the primordial sound Om.',
    descriptionKey: 'sessionsList.omMeditation.description',
    languageCode: 'en',
    durationSeconds: 720, // 12 minutes
    level: 2,
    cultureTag: 'vedic',
    instructionId: 'level2_breath_counting', // Mantra-based focus instruction
    ambientFrequency: 432,
    chimeFrequency: 528,
    createdAt: new Date().toISOString(),
  },
  {
    id: 121,
    title: 'Transcendental Meditation',
    titleKey: 'sessionsList.transcendentalMeditation.title',
    description: 'Settle into deep inner silence with mantra practice.',
    descriptionKey: 'sessionsList.transcendentalMeditation.description',
    languageCode: 'en',
    durationSeconds: 1200, // 20 minutes
    level: 3,
    cultureTag: 'vedic',
    instructionId: 'level3_mindfulness', // Deep meditation instruction
    ambientFrequency: 432,
    chimeFrequency: 528,
    createdAt: new Date().toISOString(),
  },
  {
    id: 122,
    title: 'Chakra Awareness',
    titleKey: 'sessionsList.chakraAwareness.title',
    description: 'Journey through the seven energy centers.',
    descriptionKey: 'sessionsList.chakraAwareness.description',
    languageCode: 'en',
    durationSeconds: 900, // 15 minutes
    level: 2,
    cultureTag: 'vedic',
    instructionId: 'level1_body_scan', // Body scanning for chakras
    ambientFrequency: 432,
    chimeFrequency: 528,
    createdAt: new Date().toISOString(),
  },

  // Taoist (Chinese)
  {
    id: 130,
    title: 'Qigong Meditation',
    titleKey: 'sessionsList.qigongMeditation.title',
    description: 'Cultivate Qi energy through breath and visualization.',
    descriptionKey: 'sessionsList.qigongMeditation.description',
    languageCode: 'en',
    durationSeconds: 900, // 15 minutes
    level: 2,
    cultureTag: 'taoist',
    instructionId: 'level2_breath_counting', // Breath and energy cultivation
    ambientFrequency: 432,
    chimeFrequency: 528,
    createdAt: new Date().toISOString(),
  },
  {
    id: 131,
    title: 'Inner Smile Practice',
    titleKey: 'sessionsList.innerSmilePractice.title',
    description: 'Taoist meditation for cultivating inner peace and joy.',
    descriptionKey: 'sessionsList.innerSmilePractice.description',
    languageCode: 'en',
    durationSeconds: 720, // 12 minutes
    level: 2,
    cultureTag: 'taoist',
    instructionId: 'level3_loving_kindness', // Heart-centered practice
    ambientFrequency: 528,
    chimeFrequency: 528,
    createdAt: new Date().toISOString(),
  },
  {
    id: 132,
    title: 'Wu Wei - Effortless Being',
    titleKey: 'sessionsList.wuWeiEffortlessBeing.title',
    description: 'Flow with the natural way of things.',
    descriptionKey: 'sessionsList.wuWeiEffortlessBeing.description',
    languageCode: 'en',
    durationSeconds: 1200, // 20 minutes
    level: 3,
    cultureTag: 'taoist',
    instructionId: 'level4_open_awareness', // Effortless awareness
    ambientFrequency: 432,
    chimeFrequency: 528,
    createdAt: new Date().toISOString(),
  },

  // Sufi (Islamic)
  {
    id: 140,
    title: 'Dhikr - Remembrance',
    titleKey: 'sessionsList.dhikrRemembrance.title',
    description: 'Rhythmic remembrance of the Divine.',
    descriptionKey: 'sessionsList.dhikrRemembrance.description',
    languageCode: 'en',
    durationSeconds: 900, // 15 minutes
    level: 2,
    cultureTag: 'sufi',
    instructionId: 'level2_breath_counting', // Rhythmic repetition practice
    ambientFrequency: 528,
    chimeFrequency: 528,
    createdAt: new Date().toISOString(),
  },
  {
    id: 141,
    title: 'Muraqaba - Heart Meditation',
    titleKey: 'sessionsList.muraqabaHeartMeditation.title',
    description: 'Sufi contemplation of the heart center.',
    descriptionKey: 'sessionsList.muraqabaHeartMeditation.description',
    languageCode: 'en',
    durationSeconds: 1200, // 20 minutes
    level: 3,
    cultureTag: 'sufi',
    instructionId: 'level3_loving_kindness', // Heart-centered meditation
    ambientFrequency: 528,
    chimeFrequency: 528,
    createdAt: new Date().toISOString(),
  },
  {
    id: 142,
    title: 'Breath of Compassion',
    titleKey: 'sessionsList.breathOfCompassion.title',
    description: 'Sufi breathing practice for opening the heart.',
    descriptionKey: 'sessionsList.breathOfCompassion.description',
    languageCode: 'en',
    durationSeconds: 720, // 12 minutes
    level: 2,
    cultureTag: 'sufi',
    instructionId: 'level3_loving_kindness', // Compassionate breathing
    ambientFrequency: 528,
    chimeFrequency: 528,
    createdAt: new Date().toISOString(),
  },

  // Christian Contemplative
  {
    id: 150,
    title: 'Centering Prayer',
    titleKey: 'sessionsList.centeringPrayer.title',
    description: 'Silent communion with God through sacred word.',
    descriptionKey: 'sessionsList.centeringPrayer.description',
    languageCode: 'en',
    durationSeconds: 1200, // 20 minutes
    level: 2,
    cultureTag: 'christian',
    instructionId: 'level3_mindfulness', // Contemplative silence
    ambientFrequency: 528,
    chimeFrequency: 528,
    createdAt: new Date().toISOString(),
  },
  {
    id: 151,
    title: 'Lectio Divina',
    titleKey: 'sessionsList.lectioDivina.title',
    description: 'Contemplative scripture reading and meditation.',
    descriptionKey: 'sessionsList.lectioDivina.description',
    languageCode: 'en',
    durationSeconds: 900, // 15 minutes
    level: 2,
    cultureTag: 'christian',
    instructionId: 'level2_breath_counting', // Contemplative reading instruction
    ambientFrequency: 528,
    chimeFrequency: 528,
    createdAt: new Date().toISOString(),
  },
  {
    id: 152,
    title: 'Contemplative Silence',
    titleKey: 'sessionsList.contemplativeSilence.title',
    description: 'Rest in the presence of the Divine.',
    descriptionKey: 'sessionsList.contemplativeSilence.description',
    languageCode: 'en',
    durationSeconds: 1500, // 25 minutes
    level: 3,
    cultureTag: 'christian',
    instructionId: 'level3_mindfulness', // Silent contemplation instruction
    ambientFrequency: 528,
    chimeFrequency: 528,
    createdAt: new Date().toISOString(),
  },
  {
    id: 153,
    title: 'Breath Prayer',
    titleKey: 'sessionsList.breathPrayer.title',
    description: 'Rhythmic prayer synchronized with breathing.',
    descriptionKey: 'sessionsList.breathPrayer.description',
    languageCode: 'en',
    durationSeconds: 600, // 10 minutes
    level: 1,
    cultureTag: 'christian',
    instructionId: 'level1_breath', // Breath prayer instruction
    ambientFrequency: 528,
    chimeFrequency: 528,
    createdAt: new Date().toISOString(),
  },
];
